name: CI/CD Pipeline

on:
  push:
    branches:
       - master

jobs:
  build-and-deploy:
    run-on: ubuntu-latest

     steps:
     - name: checkout code
       user: action/checkout@v2

     - name: Set up Docker Builx
       user: docker/setup-buildx-action@v1


     - name: Login to DockerHub
       user: docker/login-action@v1
       with:
         username: ${{ secrets.Docker_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t surajn17/backend ./backend
          docker build -t surajn17/frontend ./frontend
          docker push surajn17/backend
          docker push surajn17/frontend
